# Generated by Django 5.2.4 on 2026-05-30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_publico",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador público para compartir la evaluación sin exponer el ID interno.",
                        unique=True,
                    ),
                ),
                (
                    "rubro",
                    models.CharField(
                        choices=[
                            ("tecnologia", "Tecnología"),
                            ("gastronomia", "Gastronomía"),
                            ("retail", "Retail"),
                            ("salud", "Salud"),
                            ("educacion", "Educación"),
                            ("servicios", "Servicios"),
                            ("sustentabilidad", "Sustentabilidad"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ciudad", models.CharField(max_length=100)),
                (
                    "publico",
                    models.CharField(max_length=200, verbose_name="público objetivo"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(30)]
                    ),
                ),
                ("presupuesto_disponible", models.CharField(blank=True, max_length=50)),
                ("resultado", models.JSONField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("listo", "Listo"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "evaluación",
                "verbose_name_plural": "evaluaciones",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado", "creado_en"],
                        name="eval_estado_creado_idx",
                    ),
                ],
            },
        ),
    ]
