# Generated by Django 4.2.30 on 2026-05-30 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "rubro",
                    models.CharField(
                        choices=[
                            ("tecnologia", "Tecnología"),
                            ("gastronomia", "Gastronomía"),
                            ("retail", "Retail"),
                            ("salud", "Salud"),
                            ("educacion", "Educación"),
                            ("servicios", "Servicios"),
                            ("sustentabilidad", "Sustentabilidad"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("publico", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("ciudad", models.CharField(max_length=100)),
                ("presupuesto_disponible", models.CharField(blank=True, max_length=50)),
                ("resultado", models.JSONField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("listo", "Listo"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
